version: '3.8'

services:
  postgresql:
    image: postgres:15.7
    container_name: "gestor-pedidos-postgres"
    restart: always
    environment:
      POSTGRES_DB: gestorpedidos
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - db_network
    ports:
      - '5432:5432'

  mongodb:
    image: mongo:latest
    container_name: "gestor-pedidos-mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: gestorpedidos
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - db_network

  mongoexpress:
    image: mongo-express:latest
    container_name: "gestor-pedidos-mongo-express"
    restart: always
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - '8081:8081'
    networks:
      - db_network

volumes:
  postgresql_data:
  mongodb_data:

networks:
  db_network:
